version: '3.9'

services:
  db:
    image: postgres:14
    container_name: swift-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: swift
    ports:
      - "5432:5432"
    volumes:
      - swift-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: swift-api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_URL: postgres://postgres:password@db:5432/swift?sslmode=disable
    working_dir: /app
    restart: unless-stopped

volumes:
  swift-data:
