services:
  swift-db:
    image: postgres:15
    container_name: swift-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: swift
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  swift-api:
    build: .
    container_name: swift-api
    depends_on:
      swift-db:
        condition: service_healthy
    environment:
      DB_URL: postgres://postgres:mysecretpassword@swift-db:5432/swift?sslmode=disable
    ports:
      - "8080:8080"
